2018-03-09 08:33:51,518 ERROR 6364 nodejs.ClusterClientNoResponseError: client no response in 18136116ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\pass3\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 6364
hostname: USER-GALVAKJA59

2018-03-09 11:07:11,657 ERROR 6364 nodejs.ClusterClientNoResponseError: client no response in 75898ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\pass3\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 6364
hostname: USER-GALVAKJA59

2018-03-09 11:09:16,939 ERROR 10528 nodejs.ClusterClientNoResponseError: client no response in 78984ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\pass3\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 10528
hostname: USER-GALVAKJA59

2018-03-09 11:14:30,588 ERROR 11864 nodejs.ClusterClientNoResponseError: client no response in 78934ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\pass3\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 11864
hostname: USER-GALVAKJA59

2018-03-09 11:26:25,531 ERROR 10516 nodejs.ClusterClientNoResponseError: client no response in 77482ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\pass3\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 10516
hostname: USER-GALVAKJA59

2018-03-09 11:31:21,235 ERROR 9544 nodejs.ClusterClientNoResponseError: client no response in 78946ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\pass3\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 9544
hostname: USER-GALVAKJA59

2018-03-09 11:34:01,239 ERROR 9544 nodejs.ClusterClientNoResponseError: client no response in 77982ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\pass3\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 9544
hostname: USER-GALVAKJA59

2018-03-09 16:42:45,386 ERROR 9864 [-/127.0.0.1/-/2ms GET /partyclass?class=%E8%AE%BE%E5%A4%87] nodejs.SyntaxError: Identifier 'result' has already been declared
    at callController (E:\JS\pass3\node_modules\egg-core\lib\loader\mixin\controller.js:125:18)
    at callController.next (<anonymous>)
    at onFulfilled (E:\JS\pass3\node_modules\co\index.js:65:19)
    at E:\JS\pass3\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (E:\JS\pass3\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\JS\pass3\node_modules\co\index.js:118:63)
    at next (E:\JS\pass3\node_modules\co\index.js:99:29)
    at onFulfilled (E:\JS\pass3\node_modules\co\index.js:69:7)
    at E:\JS\pass3\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (E:\JS\pass3\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\JS\pass3\node_modules\co\index.js:118:63)
    at next (E:\JS\pass3\node_modules\co\index.js:99:29)
    at onFulfilled (E:\JS\pass3\node_modules\co\index.js:69:7)
    at <anonymous>

pid: 9864
hostname: USER-GALVAKJA59

2018-03-09 16:55:33,625 ERROR 9864 [-/127.0.0.1/-/1ms GET /partyclass?class=%E8%AE%BE%E5%A4%87] nodejs.SyntaxError: Identifier 'result' has already been declared
    at callController (E:\JS\pass3\node_modules\egg-core\lib\loader\mixin\controller.js:125:18)
    at callController.next (<anonymous>)
    at onFulfilled (E:\JS\pass3\node_modules\co\index.js:65:19)
    at E:\JS\pass3\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (E:\JS\pass3\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\JS\pass3\node_modules\co\index.js:118:63)
    at next (E:\JS\pass3\node_modules\co\index.js:99:29)
    at onFulfilled (E:\JS\pass3\node_modules\co\index.js:69:7)
    at E:\JS\pass3\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (E:\JS\pass3\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\JS\pass3\node_modules\co\index.js:118:63)
    at next (E:\JS\pass3\node_modules\co\index.js:99:29)
    at onFulfilled (E:\JS\pass3\node_modules\co\index.js:69:7)
    at <anonymous>

pid: 9864
hostname: USER-GALVAKJA59

2018-03-09 16:56:34,144 ERROR 9864 [-/127.0.0.1/-/1ms GET /partyclass?class=%E8%AE%BE%E5%A4%87] nodejs.SyntaxError: Identifier 'result' has already been declared
    at callController (E:\JS\pass3\node_modules\egg-core\lib\loader\mixin\controller.js:125:18)
    at callController.next (<anonymous>)
    at onFulfilled (E:\JS\pass3\node_modules\co\index.js:65:19)
    at E:\JS\pass3\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (E:\JS\pass3\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\JS\pass3\node_modules\co\index.js:118:63)
    at next (E:\JS\pass3\node_modules\co\index.js:99:29)
    at onFulfilled (E:\JS\pass3\node_modules\co\index.js:69:7)
    at E:\JS\pass3\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (E:\JS\pass3\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\JS\pass3\node_modules\co\index.js:118:63)
    at next (E:\JS\pass3\node_modules\co\index.js:99:29)
    at onFulfilled (E:\JS\pass3\node_modules\co\index.js:69:7)
    at <anonymous>

pid: 9864
hostname: USER-GALVAKJA59

2018-03-09 16:56:48,153 ERROR 9864 [-/127.0.0.1/-/1ms GET /partyclass?class=%E8%AE%BE%E5%A4%87] nodejs.SyntaxError: Identifier 'result' has already been declared
    at callController (E:\JS\pass3\node_modules\egg-core\lib\loader\mixin\controller.js:125:18)
    at callController.next (<anonymous>)
    at onFulfilled (E:\JS\pass3\node_modules\co\index.js:65:19)
    at E:\JS\pass3\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (E:\JS\pass3\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\JS\pass3\node_modules\co\index.js:118:63)
    at next (E:\JS\pass3\node_modules\co\index.js:99:29)
    at onFulfilled (E:\JS\pass3\node_modules\co\index.js:69:7)
    at E:\JS\pass3\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (E:\JS\pass3\node_modules\co\index.js:50:10)
    at Object.toPromise (E:\JS\pass3\node_modules\co\index.js:118:63)
    at next (E:\JS\pass3\node_modules\co\index.js:99:29)
    at onFulfilled (E:\JS\pass3\node_modules\co\index.js:69:7)
    at <anonymous>

pid: 9864
hostname: USER-GALVAKJA59

