2018-02-28 06:47:46,552 ERROR 12804 nodejs.ClusterClientNoResponseError: client no response in 18818860ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\JS\pass3\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 12804
hostname: ghm-pc

2018-02-28 06:48:19,027 ERROR 12804 nodejs.DisconnectedError: [egg-mongoose]Ran out of retries trying to reconnect to "localhost:27017". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.
    at new DisconnectedError (D:\JS\pass3\node_modules\mongoose\lib\error\disconnected.js:22:11)
    at Server.<anonymous> (D:\JS\pass3\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:64:31)
    at emitOne (events.js:121:20)
    at Server.emit (events.js:211:7)
    at Pool.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\topologies\server.js:327:16)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\pool.js:317:16)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
message: '[egg-mongoose]Ran out of retries trying to reconnect to "localhost:27017". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.'
name: 'DisconnectedError'
pid: 12804
hostname: ghm-pc

2018-02-28 06:57:36,778 ERROR 16288 [egg-mongoose] mongodb://localhost:27017/test disconnected
2018-02-28 06:57:36,792 ERROR 16288 nodejs.MongoError: [egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]
    at Pool.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
name: 'MongoError'
message: '[egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]'
pid: 16288
hostname: ghm-pc

2018-02-28 07:00:13,577 ERROR 7680 [egg-mongoose] mongodb://localhost:27017/test disconnected
2018-02-28 07:00:13,592 ERROR 7680 nodejs.MongoError: [egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]
    at Pool.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
name: 'MongoError'
message: '[egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]'
pid: 7680
hostname: ghm-pc

2018-02-28 07:05:45,465 ERROR 20880 [egg-mongoose] mongodb://localhost:27017/test disconnected
2018-02-28 07:05:45,479 ERROR 20880 nodejs.MongoError: [egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]
    at Pool.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
name: 'MongoError'
message: '[egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]'
pid: 20880
hostname: ghm-pc

2018-02-28 07:16:44,226 ERROR 7884 [egg-mongoose] mongodb://localhost:27017/test disconnected
2018-02-28 07:16:44,235 ERROR 7884 nodejs.MongoError: [egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]
    at Pool.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
name: 'MongoError'
message: '[egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]'
pid: 7884
hostname: ghm-pc

2018-02-28 07:19:49,477 ERROR 14088 [egg-mongoose] mongodb://localhost:27017/test disconnected
2018-02-28 07:19:49,519 ERROR 14088 nodejs.MongoError: [egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]
    at Pool.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
name: 'MongoError'
message: '[egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]'
pid: 14088
hostname: ghm-pc

2018-02-28 07:21:00,396 ERROR 3112 [egg-mongoose] mongodb://localhost:27017/test disconnected
2018-02-28 07:21:00,419 ERROR 3112 nodejs.MongoError: [egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]
    at Pool.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
name: 'MongoError'
message: '[egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]'
pid: 3112
hostname: ghm-pc

2018-02-28 07:24:07,925 ERROR 14236 [egg-mongoose] mongodb://localhost:27017/test disconnected
2018-02-28 07:24:07,939 ERROR 14236 nodejs.MongoError: [egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]
    at Pool.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
name: 'MongoError'
message: '[egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]'
pid: 14236
hostname: ghm-pc

2018-02-28 07:25:31,274 ERROR 14248 [egg-mongoose] mongodb://localhost:27017/test disconnected
2018-02-28 07:25:31,287 ERROR 14248 nodejs.MongoError: [egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]
    at Pool.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
name: 'MongoError'
message: '[egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]'
pid: 14248
hostname: ghm-pc

2018-02-28 08:26:52,630 ERROR 16756 nodejs.ClusterClientNoResponseError: client no response in 2689839ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\JS\pass3\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 16756
hostname: ghm-pc

2018-02-28 08:30:16,451 ERROR 3620 [egg-mongoose] mongodb://localhost:27017/test disconnected
2018-02-28 08:30:16,497 ERROR 3620 nodejs.MongoError: [egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]
    at Pool.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (D:\JS\pass3\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
name: 'MongoError'
message: '[egg-mongoose]failed to connect to server [localhost:27017] on first connect [MongoError: getaddrinfo ENOENT localhost:27017]'
pid: 3620
hostname: ghm-pc

2018-02-28 14:52:25,558 ERROR 8476 nodejs.ClusterClientNoResponseError: client no response in 20384648ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\JS\pass3\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 8476
hostname: ghm-pc

2018-02-28 16:48:41,998 ERROR 3104 [-/127.0.0.1/-/7ms GET /requirement?] nodejs.SyntaxError: Identifier 'sorter' has already been declared
    at callController (D:\JS\pass3\node_modules\egg-core\lib\loader\mixin\controller.js:125:18)
    at callController.next (<anonymous>)
    at onFulfilled (D:\JS\pass3\node_modules\co\index.js:65:19)
    at D:\JS\pass3\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\pass3\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\pass3\node_modules\co\index.js:118:63)
    at next (D:\JS\pass3\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\pass3\node_modules\co\index.js:69:7)
    at D:\JS\pass3\node_modules\co\index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (D:\JS\pass3\node_modules\co\index.js:50:10)
    at Object.toPromise (D:\JS\pass3\node_modules\co\index.js:118:63)
    at next (D:\JS\pass3\node_modules\co\index.js:99:29)
    at onFulfilled (D:\JS\pass3\node_modules\co\index.js:69:7)
    at <anonymous>

pid: 3104
hostname: ghm-pc

2018-03-02 15:47:11,560 ERROR 4928 nodejs.ClusterClientNoResponseError: client no response in 1747600ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (E:\JS\pass3\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 4928
hostname: USER-GALVAKJA59

2018-03-04 07:30:13,051 ERROR 11248 nodejs.ClusterClientNoResponseError: client no response in 28620522ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (D:\JS\pass3\node_modules\cluster-client\lib\leader.js:73:23)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
name: 'ClusterClientNoResponseError'
pid: 11248
hostname: ghm-pc

